# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RunMorbidityModel <- function(pars, runtime, wormburden_female, wormburden_male, cumulative_wormburden_female, cumulative_wormburden_male) {
    .Call(`_SchistoMorbidityModel_RunMorbidityModel`, pars, runtime, wormburden_female, wormburden_male, cumulative_wormburden_female, cumulative_wormburden_male)
}

rcpp_hello_world <- function() {
    .Call(`_SchistoMorbidityModel_rcpp_hello_world`)
}

